# Generated by Django 3.0.8 on 2020-11-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_confirmstring'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='key',
        ),
        migrations.AddField(
            model_name='equipment',
            name='key',
            field=models.CharField(default='a', max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='descript',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='user',
            field=models.ManyToManyField(blank=True, to='account.User'),
        ),
    ]
