# Generated by Django 3.0.8 on 2020-11-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201124_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='descript',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
